In [28]:


import numpy as np 
import pandas as pd 



import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))


In [29]:
import numpy as np
import pandas as pd
data=pd.read_csv('hypothyroid.csv')
data.head()

age sex on thyroxine query on thyroxine on antithyroid medication sick  \
0  41   F            f                  f                         f    f   
1  23   F            f                  f                         f    f   
2  46   M            f                  f                         f    f   
3  70   F            t                  f                         f    f   
4  70   F            f                  f                         f    f   

  pregnant thyroid surgery I131 treatment query hypothyroid  ... TT4 measured  \
0        f               f              f                 f  ...            t   
1        f               f              f                 f  ...            t   
2        f               f              f                 f  ...            t   
3        f               f              f                 f  ...            t   
4        f               f              f                 f  ...            t   

   TT4 T4U measured   T4U FTI measured  FTI TBG measured TBG referral source  \
0  125            t  1.14            t  109            f   ?            SVHC   
1  102            f     ?            f    ?            f   ?           other   
2  109            t  0.91            t  120            f   ?           other   
3  175            f     ?            f    ?            f   ?           other   
4   61            t  0.87            t   70            f   ?             SVI   

  binaryClass  
0           P  
1           P  
2           P  
3           P  
4           P  

[5 rows x 30 columns]

In [30]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3772 entries, 0 to 3771
Data columns (total 30 columns):
 #   Column                     Non-Null Count  Dtype 
---  ------                     --------------  ----- 
 0   age                        3772 non-null   object
 1   sex                        3772 non-null   object
 2   on thyroxine               3772 non-null   object
 3   query on thyroxine         3772 non-null   object
 4   on antithyroid medication  3772 non-null   object
 5   sick                       3772 non-null   object
 6   pregnant                   3772 non-null   object
 7   thyroid surgery            3772 non-null   object
 8   I131 treatment             3772 non-null   object
 9   query hypothyroid          3772 non-null   object
 10  query hyperthyroid         3772 non-null   object
 11  lithium                    3772 non-null   object
 12  goitre                     3772 non-null   object
 13  tumor                      3772 non-null   object
 14  hypopitu

In [31]:
from sklearn.preprocessing import LabelEncoder
enc=LabelEncoder()
for x in data.columns:
    data[x]=enc.fit_transform(data[x])
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3772 entries, 0 to 3771
Data columns (total 30 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   age                        3772 non-null   int32
 1   sex                        3772 non-null   int32
 2   on thyroxine               3772 non-null   int32
 3   query on thyroxine         3772 non-null   int32
 4   on antithyroid medication  3772 non-null   int32
 5   sick                       3772 non-null   int32
 6   pregnant                   3772 non-null   int32
 7   thyroid surgery            3772 non-null   int32
 8   I131 treatment             3772 non-null   int32
 9   query hypothyroid          3772 non-null   int32
 10  query hyperthyroid         3772 non-null   int32
 11  lithium                    3772 non-null   int32
 12  goitre                     3772 non-null   int32
 13  tumor                      3772 non-null   int32
 14  hypopituitary           

In [32]:
data.head()

age  sex  on thyroxine  query on thyroxine  on antithyroid medication  \
0   34    1             0                   0                          0   
1   15    1             0                   0                          0   
2   40    2             0                   0                          0   
3   67    1             1                   0                          0   
4   67    1             0                   0                          0   

   sick  pregnant  thyroid surgery  I131 treatment  query hypothyroid  ...  \
0     0         0                0               0                  0  ...   
1     0         0                0               0                  0  ...   
2     0         0                0               0                  0  ...   
3     0         0                0               0                  0  ...   
4     0         0                0               0                  0  ...   

   TT4 measured  TT4  T4U measured  T4U  FTI measured  FTI  TBG measured  TBG  \
0             1   28             1   72             1   10             0    0   
1             1    3             0  146             0  234             0    0   
2             1   10             1   48             1   22             0    0   
3             1   83             0  146             0  234             0    0   
4             1  201             1   44             1  199             0    0   

   referral source  binaryClass  
0                1            1  
1                4            1  
2                4            1  
3                4            1  
4                3            1  

[5 rows x 30 columns]

In [33]:
data=data.drop_duplicates()
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3711 entries, 0 to 3771
Data columns (total 30 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   age                        3711 non-null   int32
 1   sex                        3711 non-null   int32
 2   on thyroxine               3711 non-null   int32
 3   query on thyroxine         3711 non-null   int32
 4   on antithyroid medication  3711 non-null   int32
 5   sick                       3711 non-null   int32
 6   pregnant                   3711 non-null   int32
 7   thyroid surgery            3711 non-null   int32
 8   I131 treatment             3711 non-null   int32
 9   query hypothyroid          3711 non-null   int32
 10  query hyperthyroid         3711 non-null   int32
 11  lithium                    3711 non-null   int32
 12  goitre                     3711 non-null   int32
 13  tumor                      3711 non-null   int32
 14  hypopituitary           

In [34]:
data.describe()

age          sex  on thyroxine  query on thyroxine  \
count  3711.000000  3711.000000   3711.000000         3711.000000   
mean     46.493937     1.266505      0.125034            0.013473   
std      20.863642     0.525220      0.330802            0.115306   
min       0.000000     0.000000      0.000000            0.000000   
25%      28.000000     1.000000      0.000000            0.000000   
50%      50.000000     1.000000      0.000000            0.000000   
75%      63.000000     2.000000      0.000000            0.000000   
max      93.000000     2.000000      1.000000            1.000000   

       on antithyroid medication         sick     pregnant  thyroid surgery  \
count                3711.000000  3711.000000  3711.000000      3711.000000   
mean                    0.011318     0.039612     0.014282         0.014282   
std                     0.105795     0.195072     0.118666         0.118666   
min                     0.000000     0.000000     0.000000         0.000000   
25%                     0.000000     0.000000     0.000000         0.000000   
50%                     0.000000     0.000000     0.000000         0.000000   
75%                     0.000000     0.000000     0.000000         0.000000   
max                     1.000000     1.000000     1.000000         1.000000   

       I131 treatment  query hypothyroid  ...  TT4 measured          TT4  \
count     3711.000000        3711.000000  ...   3711.000000  3711.000000   
mean         0.015899           0.063056  ...      0.953921   119.133118   
std          0.125100           0.243096  ...      0.209685    98.238113   
min          0.000000           0.000000  ...      0.000000     0.000000   
25%          0.000000           0.000000  ...      1.000000    21.000000   
50%          0.000000           0.000000  ...      1.000000    79.000000   
75%          0.000000           0.000000  ...      1.000000   226.000000   
max          1.000000           1.000000  ...      1.000000   241.000000   

       T4U measured          T4U  FTI measured          FTI  TBG measured  \
count   3711.000000  3711.000000   3711.000000  3711.000000        3711.0   
mean       0.911884    64.854756      0.912423   108.715980           0.0   
std        0.283502    31.330172      0.282718    97.032357           0.0   
min        0.000000     0.000000      0.000000     0.000000           0.0   
25%        1.000000    46.000000      1.000000    17.000000           0.0   
50%        1.000000    57.000000      1.000000    56.000000           0.0   
75%        1.000000    71.000000      1.000000   221.000000           0.0   
max        1.000000   146.000000      1.000000   234.000000           0.0   

          TBG  referral source  binaryClass  
count  3711.0      3711.000000  3711.000000  
mean      0.0         3.267583     0.921584  
std       0.0         1.097079     0.268861  
min       0.0         0.000000     0.000000  
25%       0.0         3.000000     1.000000  
50%       0.0         4.000000     1.000000  
75%       0.0         4.000000     1.000000  
max       0.0         4.000000     1.000000  

[8 rows x 30 columns]

In [35]:
data['age']=(data['age']-data['age'].min())/(data['age'].max()-data['age'].min())
data['TT4']=(data['TT4']-data['TT4'].min())/(data['TT4'].max()-data['TT4'].min())
data['T4U']=(data['T4U']-data['T4U'].min())/(data['T4U'].max()-data['T4U'].min())
data['FTI']=(data['FTI']-data['FTI'].min())/(data['FTI'].max()-data['FTI'].min())


In [36]:
data.head()

age  sex  on thyroxine  query on thyroxine  on antithyroid medication  \
0  0.365591    1             0                   0                          0   
1  0.161290    1             0                   0                          0   
2  0.430108    2             0                   0                          0   
3  0.720430    1             1                   0                          0   
4  0.720430    1             0                   0                          0   

   sick  pregnant  thyroid surgery  I131 treatment  query hypothyroid  ...  \
0     0         0                0               0                  0  ...   
1     0         0                0               0                  0  ...   
2     0         0                0               0                  0  ...   
3     0         0                0               0                  0  ...   
4     0         0                0               0                  0  ...   

   TT4 measured       TT4  T4U measured       T4U  FTI measured       FTI  \
0             1  0.116183             1  0.493151             1  0.042735   
1             1  0.012448             0  1.000000             0  1.000000   
2             1  0.041494             1  0.328767             1  0.094017   
3             1  0.344398             0  1.000000             0  1.000000   
4             1  0.834025             1  0.301370             1  0.850427   

   TBG measured  TBG  referral source  binaryClass  
0             0    0                1            1  
1             0    0                4            1  
2             0    0                4            1  
3             0    0                4            1  
4             0    0                3            1  

[5 rows x 30 columns]

In [37]:
y=data['binaryClass']
x=data.drop(['binaryClass'],axis=1)

In [38]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest= train_test_split(x,y,test_size=0.1,stratify=y)
print(xtrain.shape)
print(xtest.shape)
print(ytrain.shape)
print(ytest.shape)

(3339, 29)
(372, 29)
(3339,)
(372,)


In [39]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report


In [40]:
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from scipy import sparse
from scipy.sparse import csr_matrix
from sklearn.linear_model import LogisticRegression

In [41]:
logreg = LogisticRegression()
logreg.fit(xtrain, ytrain)
logreg_predict = logreg.predict(xtest)
logreg_acc = accuracy_score(logreg_predict, ytest)
print("Test accuracy:{:.2f}%".format(logreg_acc*100))

Test accuracy:93.28%


C:\Users\SUJON\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [42]:
print(confusion_matrix(ytest, logreg_predict))
print("\n")
print(classification_report(ytest, logreg_predict))

[[ 11  18]
 [  7 336]]


              precision    recall  f1-score   support

           0       0.61      0.38      0.47        29
           1       0.95      0.98      0.96       343

    accuracy                           0.93       372
   macro avg       0.78      0.68      0.72       372
weighted avg       0.92      0.93      0.93       372



In [43]:
dt =  DecisionTreeClassifier()
dt.fit(xtrain, ytrain)
dt_predict = dt.predict(xtest)
dt_acc = accuracy_score(dt_predict, ytest)
print("Test accuracy:{:.2f}%".format(dt_acc*100))

Test accuracy:97.85%


In [44]:
print(confusion_matrix(ytest, dt_predict))
print("\n")
print(classification_report(ytest, dt_predict))

[[ 26   3]
 [  5 338]]


              precision    recall  f1-score   support

           0       0.84      0.90      0.87        29
           1       0.99      0.99      0.99       343

    accuracy                           0.98       372
   macro avg       0.91      0.94      0.93       372
weighted avg       0.98      0.98      0.98       372



In [45]:
knn = KNeighborsClassifier()
knn.fit(xtrain, ytrain)
knn_predict = knn.predict(xtest)
knn_acc = accuracy_score(knn_predict, ytest)
print("Test accuracy:{:.2f}%".format(knn_acc*100))

Test accuracy:97.58%


C:\Users\SUJON\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [46]:
print(confusion_matrix(ytest, knn_predict))
print("\n")
print(classification_report(ytest, knn_predict))

[[ 22   7]
 [  2 341]]


              precision    recall  f1-score   support

           0       0.92      0.76      0.83        29
           1       0.98      0.99      0.99       343

    accuracy                           0.98       372
   macro avg       0.95      0.88      0.91       372
weighted avg       0.97      0.98      0.97       372



Since the model has performed well on the test set, it doesnt require any hyperparameter tuning.

In [47]:
svm = SVC()
svm.fit(xtrain, ytrain)
svm_predict = svm.predict(xtest)
svm_acc = accuracy_score(svm_predict, ytest)
print("Test accuracy:{:.2f}%".format(svm_acc*100))

Test accuracy:92.20%


In [48]:
print(confusion_matrix(ytest, svm_predict))
print("\n")
print(classification_report(ytest, svm_predict))

[[  0  29]
 [  0 343]]


              precision    recall  f1-score   support

           0       0.00      0.00      0.00        29
           1       0.92      1.00      0.96       343

    accuracy                           0.92       372
   macro avg       0.46      0.50      0.48       372
weighted avg       0.85      0.92      0.88       372



C:\Users\SUJON\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\SUJON\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\SUJON\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [49]:
Rf = RandomForestClassifier()
Rf.fit(xtrain, ytrain)
Rf_predict = Rf.predict(xtest)

Rf_acc = accuracy_score(Rf_predict, ytest)
print("Test accuracy:{:.2f}%".format(Rf_acc*100))

Test accuracy:96.51%


In [51]:
print(confusion_matrix(ytest, Rf_predict))
print("\n")
print(classification_report(ytest, Rf_predict))

[[ 18  11]
 [  2 341]]


              precision    recall  f1-score   support

           0       0.90      0.62      0.73        29
           1       0.97      0.99      0.98       343

    accuracy                           0.97       372
   macro avg       0.93      0.81      0.86       372
weighted avg       0.96      0.97      0.96       372

